starknet-io/SNIPs

SIMPS/simp-1.md

:man: add jag-lotus as simp editor

---

.github/ISSUE_TEMPLATE/config.yml
README.md
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md
docs/SECURITY.md

github.com/starknet-community-libs is now github.com/starknet-io

Replace 'starknet-community-libs' with 'starknet-io' everywhere

---

SNIPS/snip-1.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/SNIPs/23)

Change ERC references to SRC

---

SNIPS/snip-5.md

This proposal suggests the implementation of a new RPC endpoint to retrieve relevant information concerning Starknet appchains.

Addition of Starknet Appchain Info RPC Endpoint

---

SNIPS/snip-8.md

Fix broken poseidon hash doc link

📝 fix broken poseidon hash doc link

---

SNIPS/snip-8.md

SNIP-8 typo

---

SNIPS/snip-1.md
SNIPS/snip-4.md
SNIPS/snip-5.md

Hello
I fixed some typos in the docs,
Hope it helps.
Br,
Tudor.

fix: minor typos

---

SNIPS/snip-9.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/SNIPs/76)

SNIP-9: Adding a new Cairo-2 compatible version for OutsideExecution type hashing

---

SNIPS/snip-12.md
SNIPS/snip-9.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/SNIPs/79)

Adding notes on revision 1 type and value mismatch

---

SNIPS/snip-12.md
SNIPS/snip-6.md

Change status of SNIP-6 and SNIP-12 to "Review"

Change status of SNIP-6 and SNIP-12 to "Review"

---

SNIPS/snip-1.md

Update snip-1 links.md

---

SNIPS/snip-18.md

Suggestion for the first steps of staking in the Starknet protocol

SNIP-18: Staking’s First Stage on Starknet

---

SNIPS/snip-9.md

Fixes an outdated link to the reference implementation

Fix snip-9 broken link

---

SNIPS/snip-14.md

updating snip-14 to reflect the new changes introduced with Tokenbound V3.

chore: update snip-14 to reflect v3 changes

---

SNIPS/snip-12.md

Fixing https://github.com/starknet-io/SNIPs/issues/117

Update snip-12.md remove extra ','

---

SNIPS/snip-6.md

deleted duplicate snip-6.md

---

SNIPS/snip-25.md

fix error snip-25.md

---

SNIPS/snip-13.md
SNIPS/snip-25.md

SNIPS/snip-13.md
Compatability - Compatibility
SNIPS/snip-25.md
comunity - community

fix errors

---

SNIPS/snip-9.md

domain_seperator - domain_separator
fixed it , thanks

fix err snip-9.md

---

SNIPS/snip-29.md

Fix the description of the array returned by 'buildTypedData' in SNIP29
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/SNIPs/147)

Fix description in "Security Considerations" of SNIP29

---

SNIPS/snip-30.md

This SNIP describes the proposed changes in the v0.14.0 upgrade of Starknet
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/starknet-io/SNIPs/148)

Add SNIP 30

---

SNIPS/snip-2.md

Hi team
https://github.com/OpenZeppelin/cairo-contracts/blob/main/src/token/erc20/erc20.cairo - old link
https://github.com/OpenZeppelin/cairo-contracts/blob/main/packages/token/src/erc20/erc20.cairo - new link

replace dead reference snip-2.md
